"project_id": "574147"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_TOKEN"

files:
  [
    {
      "source": "/src/lang/nb.json",
      "translation": "/src/lang/%two_letters_code%.json",
      "dest": "/04-qa-24/nb.json",
    },
    {
      "source": "/public/weeks/1/nb.json",
      "translation": "/public/weeks/1/%two_letters_code%.json",
      "dest": "/04-qa-24/week1.json",
    },
    {
      "source": "/public/weeks/2/nb.json",
      "translation": "/public/weeks/2/%two_letters_code%.json",
      "dest": "/04-qa-24/week2.json",
      "export_only_approved": true,
    },
  ]
