"project_id": "574147"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_TOKEN"

files:
  [
    {
      "source": "/src/lang/nb.json",
      "translation": "/src/lang/%two_letters_code%.json",
      "dest": "/04-qa-24/nb.json",
    },
  ]
