"project_id": "574147"
"base_path": "."
"base_url": "https://api.crowdin.com"
"preserve_hierarchy": true
"api_token_env": "CROWDIN_TOKEN"

files:
  [
    {
      "source": "/src/lang/nb.json",
      "translation": "/src/lang/%two_letters_code%.json",
      "dest": "/04-qa-24/nb.json",
    },
    {
      "source": "/public/weeks/1/nb.json",
      "translation": "/public/weeks/1/%two_letters_code%.json",
      "dest": "/04-qa-24/week1.json",
    },
    {
      "source": "/public/weeks/2/nb.json",
      "translation": "/public/weeks/2/%two_letters_code%.json",
      "dest": "/04-qa-24/week2.json",
      "export_only_approved": true,
    },
    {
      "source": "/public/weeks/3/nb.json",
      "translation": "/public/weeks/3/%two_letters_code%.json",
      "dest": "/04-qa-24/week3.json",
      "export_only_approved": true,
    },
    {
      "source": "/public/weeks/4/nb.json",
      "translation": "/public/weeks/4/%two_letters_code%.json",
      "dest": "/04-qa-24/week4.json",
      "export_only_approved": true,
    },
    {
      "source": "/public/weeks/5/nb.json",
      "translation": "/public/weeks/5/%two_letters_code%.json",
      "dest": "/04-qa-24/week5.json",
      "export_only_approved": true,
    },
    {
      "source": "/public/weeks/6/nb.json",
      "translation": "/public/weeks/6/%two_letters_code%.json",
      "dest": "/04-qa-24/week6.json",
      "export_only_approved": true,
    },
    {
      "source": "/public/weeks/7/nb.json",
      "translation": "/public/weeks/7/%two_letters_code%.json",
      "dest": "/04-qa-24/week7.json",
      "export_only_approved": true,
    },
    {
      "source": "/public/weeks/8/nb.json",
      "translation": "/public/weeks/8/%two_letters_code%.json",
      "dest": "/04-qa-24/week8.json",
      "export_only_approved": true,
    },
  ]
